pipeline {

  environment {
    registry = "jonesthomas/first-node-app"
    dockerimagename = "jonesthomas/first-node-app"
    dockerimagetags = "jonesthomas/first-node-app:${env.BUILD_NUMBER}"
    dockerImage = ""
  }

  agent any

  stages {

    stage('Checkout Source') {
      steps {
        git branch: 'master', credentialsId: 'Ramya-Jenkins', url: 'git@github.com:Jones-Thomas/python-flask-docker.git'
      }
    }

    stage('Build image') {
      steps{
        script {
          dockerImage = docker.build dockerimagename
        }
      }
    }

    stage('Pushing Image') {
      environment {
               registryCredential = 'jones-dockerhub'
           }
      steps{
        script {
        docker.withRegistry( '', registryCredential ) {
        dockerImage.push("${env.BUILD_NUMBER}")
            }
        }
      }
    }
    stage('Cleaning up') {
        steps{
            sh "docker rmi $dockerimagename:${env.BUILD_NUMBER}"
            sh "docker rmi $dockerimagename"
        }
    }

    stage('Deploy') {
      steps {
            sh "pwd"
            sh """
            sed -i "s|DOCKERIMAGETAGS|$dockerimagetags|g" ./Ansible/python-playbook.yml
            """
            sh "sudo ansible-playbook ./Ansible/python-playbook.yml"  // -vvvv"
            sh "pwd"
      }
    }
  }
}