---
- hosts: webservers
  become: true
  tasks:
  - name: Install Docker
    shell: |
      yum install python-pip docker -y
  - name: Add the user to the docker group
    command: usermod -a -G docker ec2-user 
  - name: Start Docker service
    service:
      name: docker
      state: started
      enabled: yes
  - name: log into docker hub registry
    command: docker login -u="jonesthomas" -p="Jonesthomas@1"
  # - name: Stop all running container
  #   # command: docker rm -f python-flask-app
  #   command: sudo docker rm -vf $(docker ps --all --quiet)
  # - name: Remove the old image
  #   # command: docker rmi DOCKERIMAGETAGS
  #   command: sudo docker rmi -f $(docker images --all --quiet)
  - name: Ensure a container is running
    command: docker run -d --name python-flask-app -p 5000:5000 DOCKERIMAGETAGS
  - name: Log out of DockerHub
    command: docker logout